### PR TITLE
graph: fix file upload control when no initial data loaded

### LINKED ISSUE #4556: graph: unable to upload a graph for viewing, when no graph in logdir
Repro:
- Find a .pbtxt graph file on the filesystem
- Launch TensorBoard at a log dir that does not contain the graph
- Open TensorBoard's Graph dashboard (after https://github.com/tensorflow/tensorboard/pull/4538, the sidebar should be visible)
- Click "Upload file" and open the .pbtxt from filesystem

Actual: the graph file does not load or get rendered
Expected: the .pbtxt should load

### PR DESCRIPTION
**Pull request by japie1235813**
* Motivation for features / changes
Fix file upload control function (fixes #4556 #1613)

* Technical description of changes
Previously the board render either the graphboard or no-data messages. Now it renders both and uses css display to control their appearances.
* Screenshots of UI changes
Select file:
selectFile
Normal loading:
Screen Shot 2021-01-28 at 1 52 56 PM

### CODE REVIEW

File: tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts [hunk 1]
```diff
@@ -88,62 +88,58 @@ class TfGraphDashboard extends LegacyElementMixin(PolymerElement) {
...
+          selected-file="[[_selectedFile]]"
+          out-graph-hierarchy="{{_graphHierarchy}}"
+          out-graph="{{_graph}}"
+          out-stats="{{_stats}}"
+          progress="{{_progress}}"
+          hierarchy-params="[[_hierarchyParams]]"
+          compatibility-provider="[[_compatibilityProvider]]"
+        ></tf-graph-dashboard-loader>
+        <div
+          class$="no-data-message [[_showComponent(_selectedFile, _datasets, 'false')]]"
```
Comment (stephanwlee) [inline tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts:104]: Two related things.

1. Since we render `.no-data-message` and `.graphboard` all the time anyways, can we just set a class name on the outer DIV or whatever and use CSS to control whether to show `.graphboard` or `.no-data-message`?
2.  `_showComponent` is a misnomer. Sure, that is the logic you are implementing but that is not what the method is doing (it is returning a class name). Also, `_getContainerClassName` method should return a class name that describes a state instead of a generic verb, `.remove`.

**Review by stephanwlee — CHANGES_REQUESTED** [review]
Change makes sense but would like changes to the method name and CSS organization. Please refer to the comment inline.

File: tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts (hunk 1 above)
Comment (japie1235813) [reply tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts]: Thanks for the review! Please take another look. Thanks!

**Review by stephanwlee — APPROVED** [review]
LGTM. In the future, please press the reload icon there to re-request a review :) 

image
