### PR TITLE
Roll forward vulcanization printer change with check for outside-head link importing

### LINKED ISSUE #3557: Graph info panel is broken
Symptom: after the #3476 refactor, the graph info panel is broken.

Cause:
After the change, the iron-list dom-module is missing from the document. When inspecting the elements more carefully, it appears like following:

```html
    <div id="numeric-alerts-table-container">
          <table id="numeric-alerts-table">
            <thead>
              <tr>
                <th>First Offense</th>
                <th>Tensor (Device)</th>
                <th id="event-counts-th">Event Counts</th>
              </tr>
            </thead>
            <tbody id="numeric-alerts-body"></tbody>
          </table>
        </div>
      </div>
      <template is="dom-if" if="[[!_hasDebuggerNumericAlerts(debuggerNumericAlerts)]]">
        <p class="no-numeric-alerts-notification">
          No numeric alerts so far. That is likely good. Alerts indicate the
          presence of NaN or (+/-) Infinity values, which may be concerning.

<dom-module id="iron-list">
  <template>
    <style>
```

As you can notice, the DOM is quite broken. There are multiple closing tags from tf-graph-debugger-data-card are missing. 

Upon more careful debugging, I have found out that the Vulcanization is actually responsible for such structure.

For instance, `<p>foo</p>` gets compiled into `<p>foo`. Similarly, 
```html
<template>
  <p>foo</p>
</template>
<dom-module id="iron-list">
</dom-module

<!-- gets compiled to -->
<template>
  <p>foo
</template>

<dom-module id="iron-list">
</dom-module
```

When debugged further, I found that there are some heuristic on HTML5Printer of jsoup that we use which omits closing tag of certain tags when they are the last one in current level <https://github.com/bazelbuild/rules_closure/blob/d1c0bb4862882e0444ee478aa2091d41a4df084e/java/org/jsoup/nodes/Html5Printer.java#L209-L214>.

I think the intention was good but if you parse then print below code using jsoup, you get quite wrong code.
```html
<div>
  <p>foo
</div>

<!-- converts to -->
<div>
  <p>foo
```

There are three ways to move forward:
1. fix jsoup not to wrongfully remove closing tag of parent node
2. never do multiple passes of jsoup parse and print
3. use genrule to inline polymer_lib into tensorboard.html since inlining is all we need.

cc @bmd3k

### PR DESCRIPTION
**Pull request by caisq**
* Motivation for features / changes
  * Roll forward #3582 with change, in order to fix #3557.
* The solution is primarily due to @stephanwlee. When such midway imports are found,
   a `RuntimeException` is thrown with an error message describing the cause and the
   offending element.

### CODE REVIEW

File: tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java [hunk 1]
```diff
@@ -778,6 +783,125 @@ private static String extractAndTransformJavaScript(Document document, Webpath j
...
+
+    document.traverse(new FlatDocumentCopier(flatDoc));
+
+    for (Element subdoc : flatDoc.getElementsByTag("#root")) {
+      if (subdoc != flatDoc) {
+        final int MAX_ELEMENT_STR_LEN = 200;
+        String elementStr = subdoc.toString();
+        if (elementStr.length() > MAX_ELEMENT_STR_LEN) {
+          elementStr = elementStr.substring(0, MAX_ELEMENT_STR_LEN) + "...";
+        }
```
Comment (stephanwlee) [inline tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java:862]: Not sure how useful it would be to see the document as stringified. Perhaps do the `outerHtml()` or `subdoc.parent().outerHTML()`?

Comment (caisq) [reply tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java]: Good point. Done.

**Comment by caisq** [comment]
NOTE: Do not merge yet. Still resolving some internal issues.
