### PR TITLE
bug: apply new scale niceDomain to vz-line-chart

### LINKED ISSUE #4362: Constant time series with small values don't have proper axes
If I have a time series with a large, constant value f (e.g. 10.0), the y-axis scale reflects the constant value (scale goes from 0 to ~2f). However, if my value f is small (e.g. 0.01), the y-axis goes from -1.0 to 1.0, and does not at all reflect the scale of the constant.

It appears this issue was raised [here](https://github.com/tensorflow/tensorboard/pull/1507#discussion_r226418475) but not changed. I think constant curves should be made consistent - in the code where I noticed it, deviations from the known constant value were informative, and I spent a bunch of time thinking that I had a deviation (value of 0 instead of small but non-zero) due to not understanding how the plot axes were set.

Good:

image

Bad (real value of 1e-3):

image

### PR DESCRIPTION
**Pull request by stephanwlee**
We are in midst of working on the new version of the line chart. In
doing so, we rewrote a scale library with a bit more tests.

This change integrates the new scale library so small constant values do
not result (e.g., 0.05) in  [-1, 1] domain.

image

Fixes #4362.

### CODE REVIEW

File: tensorboard/components/vz_line_chart2/linear-scale.ts [hunk 1]
```diff
@@ -41,27 +45,8 @@ export class LinearScale extends Plottable.Scales.Linear implements ITfScale {
    */
```
Comment (nfelt) [inline tensorboard/components/vz_line_chart2/linear-scale.ts:45]: Can you remove the comment above, now that it's not accurate any more?

**Review by nfelt — APPROVED** [review]
LGTM.  Is there anything worth porting in the log scale?  Or I guess since it's not fixing the bug maybe not worth backporting.
